
name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'yarn'
        node-version: 10.x

    - name: yarn install and build
      run: |
        yarn install
        yarn run build