
name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.15.0'

    - name: yarn install and build
      run: |
        npm install
        npm run build

    - name: setup aliyun oss
      run: | 
        sudo wget http://gosspublic.alicdn.com/ossutil/1.7.8/ossutil32 
        pwd
        ls -l
        sudo chmod 755 ossutil32
        echo ${{ secrets.OSS_KEY_ID }}
        echo ${{ secrets.OSS_KEY_SECRET }}
        ./ossutil32 config -e oss-cn-beijing.aliyuncs.com -i ${{ secrets.OSS_KEY_ID }} -k ${{ secrets.OSS_KEY_SECRET }} -L CH 

    - name: cp files to aliyun
      run: ./ossutil32 cp -rf ./lib oss://wechat-view/element-dist/