
name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.15.0'

    - name: yarn install and build
      run: |
        npm install
        npm run build